import test from "node:test";
import assert from "node:assert/strict";
import {
  ASSET_GENERATION_JOB_VERSION,
  MEDIA_GENERATION_PROVIDER_VERSION,
} from "../src/asset-generation-domain.mjs";
import { createMemoryInfraDriver } from "../../../packages/infra/src/memory-driver.mjs";
import {
  createAssetGenerationService,
  executeAssetGenerationJob,
} from "../src/asset-generation-service.mjs";

function job() {
  return {
    jobVersion: ASSET_GENERATION_JOB_VERSION,
    jobId: "asset_job_1",
    assetKind: "image",
    role: "place",
    variant: "default",
    brief: {
      description: "A generated reconstruction of a humid neighborhood market.",
      constraints: ["Do not imply documentary evidence."],
    },
    inputReferences: ["presentation_1", "place_1"],
    referenceObjectRefs: [],
    outputObjectRef: "asset_obj_1",
    receiptObjectRef: "asset_receipt_1",
    requestedAt: "2026-08-21T20:10:11Z",
    providerProfile: "presentation-image-default-v1",
    context: { mediaId: "media_place_market", threadId: "thr_1" },
  };
}

test("AssetGenerationService schedules a deterministic workflow job instead of generating in request path", async () => {
  const infra = createMemoryInfraDriver();
  const service = createAssetGenerationService({ infra });
  const first = await service.request(job());
  const second = await service.request(job());
  assert.equal(first.instance.status, "queued");
  assert.equal(first.instance.duplicate, false);
  assert.equal(second.instance.duplicate, true);
  assert.equal(await infra.objects.head("asset_obj_1"), null);
  assert.equal(await infra.objects.head("asset_receipt_1"), null);
});

test("asset workflow stores generated bytes through InfraDriver objects and returns generation provenance", async () => {
  const infra = createMemoryInfraDriver();
  const provider = {
    providerVersion: MEDIA_GENERATION_PROVIDER_VERSION,
    providerId: "fixture-image-provider",
    capabilities: ["image"],
    async generate(request) {
      assert.equal(request.brief.description.includes("market"), true);
      assert.equal(request.variant, "default");
      assert.deepEqual(request.referenceObjects, []);
      return {
        assetKind: "image",
        bytes: new TextEncoder().encode("fake-image-bytes"),
        mediaType: "image/webp",
        width: 1024,
        height: 1024,
        durationMs: null,
        provider: "fixture",
        model: "fixture-image-v1",
        providerRequestId: "req_fixture_1",
        generatedAt: "2026-08-21T20:11:00Z",
        configuration: { size: "1024x1024" },
      };
    },
  };
  const result = await executeAssetGenerationJob({
    infra,
    provider,
    job: job(),
    now: () => "2026-08-21T20:12:00Z",
  });
  const { receipt } = result;
  assert.equal(receipt.status, "ready");
  assert.equal(receipt.objectRef, "asset_obj_1");
  assert.match(receipt.sha256, /^sha256:[0-9a-f]{64}$/);
  assert.equal(receipt.generation.provider, "fixture");
  assert.equal(receipt.generation.configuration.size, "1024x1024");
  assert.notEqual(await infra.objects.head("asset_obj_1"), null);
  assert.notEqual(await infra.objects.head("asset_receipt_1"), null);
  assert.match(result.receiptDigest, /^sha256:[0-9a-f]{64}$/);
});

test("unsupported provider capability becomes unavailable without storing fabricated output", async () => {
  const infra = createMemoryInfraDriver();
  const provider = {
    providerVersion: MEDIA_GENERATION_PROVIDER_VERSION,
    providerId: "audio-only",
    capabilities: ["audio"],
    async generate() { throw new Error("must not run"); },
  };
  const result = await executeAssetGenerationJob({
    infra,
    provider,
    job: job(),
    now: () => "2026-08-21T20:12:00Z",
  });
  const { receipt } = result;
  assert.equal(receipt.status, "unavailable");
  assert.match(receipt.unavailableReason, /does not support image/);
  assert.equal(await infra.objects.head("asset_obj_1"), null);
  assert.notEqual(await infra.objects.head("asset_receipt_1"), null);
});
