steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/deployments/content-credential-signer/cloud-run/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
